# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Neighbor Tone Concerts
email: info@neighbortoneconcerts.com
description: > # this means to ignore newlines until "baseurl:"
  Neighbor Tone Concerts is your personal assistant and marketplace for hosting a concert in your home. 
  We handle all of the dirty work so that you can relax and enjoy the experience of live, beautiful music with your friends and community. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://neighbortoneconcerts.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

#Include and Excluce
exclude: ["node_modules","less", "gulpfile.js", "package.json"]
